### ISSUE TITLE
L10n FR of tutorials/es7/observe

### ISSUE THREAD

**Issue by tdd** [html5rocks/www.html5rocks.com#1118]
Hi guys,

Before I start L10n'ing this in FR, you don't already have such an offer in the pipes, do you? Can't seem to find an existing issue, but just checking.

**Comment by tdd** [comment]
Yeah, second time. Would that be okay if I just went ahead with my own understanding (which is probably correct) and just submitted the translation for good? It's been 10 months now and I can't get Addy to sit down and do this.

**Comment by PaulKinlan** [comment]
Sounds good to me.
