### ISSUE TITLE
Animating a Million Letters article demo is broken

### ISSUE THREAD

**Issue by kig** [html5rocks/www.html5rocks.com#1264]
The demo in Animating a Million Letters article is broken due to a WebGL API implementation change that broke THREE.js a while back.

**Comment by trusktr** [comment]
it's just 404 now. :(

**Comment by duhaime** [comment]
It looks like someone posted a [fiddle](http://jsfiddle.net/ebeit303/b90z2erg/) with the original source code...

**Comment by tokee** [comment]
The fiddle referenced JavaScript libraries from html5rocks, which has since been removed. I corrected the links to cdnjs-versions and copy-pasted the sampe text into the source. (Currently) working demo at https://jsfiddle.net/mfz1pLuq/
