### ISSUE TITLE
Folder DnD example uses deprecated (webkit/blink only) API

### ISSUE THREAD

**Issue by smaug----** [html5rocks/www.html5rocks.com#1285]
http://updates.html5rocks.com/2012/07/Drag-and-drop-a-folder-onto-Chrome-now-available should be
updated to say it is using legacy non-standard APIs.

**Comment by smaug----** [comment]
Why is this closed? html5rocks.com shouldn't advocate for use of proprietary technologies.
All of FileSystem API is Google only thing.

**Comment by PaulKinlan** [comment]
Its unlikely to get fixed.
