### ISSUE TITLE
Case Study for Bullseye's Playground

### ISSUE THREAD

**Issue by konistehrad** [html5rocks/www.html5rocks.com#1320]
I'd love to do a case study for Target's [Bullseye's Playground](http://target.com/play), on which I was the lead dev. The style would be similar to that of Daniel Isaksson's excellent piece [The Hobbit Experience](http://www.html5rocks.com/en/tutorials/casestudies/hobbit/). I'll be focusing primarily on mobile optimization and novel animation/asset pipeline techniques we used while developing this product.

Thanks for your consideration!

**Comment by PaulKinlan** [comment]
@konistehrad - i've just tried replying to your email but it;s failing

**Comment by konistehrad** [comment]
@PaulKinlan Hi Paul! Unfortunately the company I was working with on this project deactivated my account a little early. I've had them reestablish the account, it should be working now.

**Comment by PaulKinlan** [comment]
Ah cool, I'll email you again :)
