### ISSUE TITLE
Privacy interstitial blocking access to https://h5r in Chrome

### ISSUE THREAD

**Issue by paulirish** [html5rocks/www.html5rocks.com#1328]
![image](https://cloud.githubusercontent.com/assets/39191/5608871/6a73d24e-9445-11e4-9ee6-49adba1d91f4.png)

The cert is for google.com and Chrome. 
If we don't support this URL we should probably redirect to avoid this. 

Our tickets tracking SSL for H5R are here: #1107  and #957 . It's not implemented.

@kdzwinel did you get this by just typing it in or https everywhere? It's actually pretty hard to get this.
(reported here https://twitter.com/kdzwinel/status/551863870323965952 )

#### results:
* http://www.html5rocks.com/ loads fine
* http://html5rocks.com/ loads fine
* https://www.html5rocks.com/ just fails normally
* https://html5rocks.com/ fails with interstitial

**Comment by PaulKinlan** [comment]
We don't have https at all on h5r. Its an open task for me to get sorted
when we get Eng time available

**Comment by kdzwinel** [comment]
It was typed in, so it's probably not a high priority. I just found it weird that it throws an error and redirects to google.com
