### ISSUE TITLE
"Applying NASA code guidelines to JS". Candidate for posting?

### ISSUE THREAD

**Issue by PixelsCommander** [html5rocks/www.html5rocks.com#1335]
Hi

Does this one  https://docs.google.com/document/d/1D3zrbUEZZfujX4IHp536_5KM6oRldl8yXdXVZqLrSNo/edit looks like a candidate for posting for your opinion? Any hints on modifications needed?

**Comment by PaulKinlan** [comment]
That's a nice doc to read, but I don't think it is for H5R.
