### ISSUE TITLE
The requested URL /2015/01/virtual-viewport was not found on this server.

### ISSUE THREAD

**Issue by napengam** [html5rocks/www.html5rocks.com#1339]
From http://www.html5rocks.com/en/

Error: Not Found
The requested URL /2015/01/virtual-viewport was not found on this server.

**Comment by PaulKinlan** [comment]
Cc @gauntface

**Comment by gauntface** [comment]
Fixed: http://updates.html5rocks.com/2015/01/virtual-viewport
