### ISSUE TITLE
RSS Feed out of date?

### ISSUE THREAD

**Issue by craigfrancis** [html5rocks/www.html5rocks.com#1343]
Can you check:

http://feeds.feedburner.com/html5rocks
http://updates.html5rocks.com/feeds/rss.xml

As the latest article it's showing is from December (How to use Service Worker), rather than Jan 20th (ES6 Template Strings).

**Comment by PaulKinlan** [comment]
That's a different rss feed. That's for updates.html5rocks.com

**Comment by craigfrancis** [comment]
Sorry, I though the feedburner was just a cache of the second url... either way, who should I contact to get it fixed?

**Comment by PaulKinlan** [comment]
Me, but it us unlikely to get fixed, we lost track of who has access to the
feedburner and we don't have a huge amount of resource to dedicate to
getting it fixed across both properites.

**Comment by craigfrancis** [comment]
Ahh, there is a separate project for that... have raised a ticket over there (sorry for duplicating):

https://github.com/html5rocks/updates.html5rocks.com.new/issues/74

But you shouldn't need to update feedburner... just getting the RSS feed on your website working should be enough :-)
