### ISSUE TITLE
RSS feed missing entries

### ISSUE THREAD

**Issue by amatriain** [html5rocks/www.html5rocks.com#1350]
The RSS icon in http://www.html5rocks.com links to http://feeds.feedburner.com/html5rocks. However this feed seems to be missing entries: the last article in the feed is "Introduction to Service Worker" from Dec 1st 2014, but there are more recent articles published on the web.

**Comment by PaulKinlan** [comment]
Those are from updates.html5rocks.com. that is a different feed.

**Comment by amatriain** [comment]
I see, there is another feed in updates.html5rocks.com which is probably what I'm interested in. Thanks for clearing up, closing this.
