### ISSUE TITLE
Aritcle to introduce offliner, a solution for supporting offline and always-up-to-date web applications.

### ISSUE THREAD

**Issue by lodr** [html5rocks/www.html5rocks.com#1361]
Motivated by the article about [sw-precache](http://updates.html5rocks.com/2015/02/offline-first-with-sw-precache), I would want to introduce [offliner](https://github.com/lodr/offliner). The approach is totally different as it's based on a sw that never changes and tries to resolve the update problem from an only-client perspective.
Furthermore, its strategy tries to mimic online web only falling back to cache when there is no network response.

**Comment by PaulKinlan** [comment]
This looks like a really cool project.  cc @jakearchibald @jeffposnick as an fyi. 

We are going through a bit of a transition on html5rocks, so I don't think it we would publish an article on this at this time.
