### ISSUE TITLE
[FREE MAGENTO QUIZ] +200 Magento Questions to develop your skills

### ISSUE THREAD

**Issue by alexnguyen123** [html5rocks/www.html5rocks.com#1407]
Hi guys,
I am Bobby Pham, a Magento developer from Magestore.
We have built a FREE Magento Test Tool for you to test your Magento skills and knowledge.
Here is the link: http://bit.ly/1OUri5R
I want to announce that it's TOTALLY FREE and you guys can have a chance to receive Magento Certification by Magestore.
We are not spamming.
Thank you so much :) We hope it will help you guys!

**Comment by WillsB3** [comment]
> We are not spamming.

This looks 100% like Spam to me.

**Comment by addyosmani** [comment]
This is completely spam. Closing.
