### ISSUE TITLE
Navigation Timing page: Broken link + image replaced by domain parking banner

### ISSUE THREAD

**Issue by kriscooke** [html5rocks/www.html5rocks.com#1461]
### Page
[Measuring Page Load Speed with Navigation Timing](https://www.html5rocks.com/en/tutorials/webperformance/basics/)

### Issue
- The site at http://66.7percentangel.com where the referenced tool was located exists no longer
- Its image assets have been replaced with this unfortunate looking banner, which shows up at the bottom of the article:

See PR #1462

<img width="1440" alt="screen shot 2016-11-06 at 8 28 54 pm" src="https://cloud.githubusercontent.com/assets/5522075/20046897/da6e6cc8-a463-11e6-9c3f-33e66bc9ed17.png">

**Comment by kaycebasques** [comment]
Fixed by #1462.
