### ISSUE TITLE
Translation into Korean: howbrowserswork 

### ISSUE THREAD

**Issue by roseline124** [html5rocks/www.html5rocks.com#1526]
Hello, staff.

I'd like to translate 'how browsers work' into Korean. is it okay?

Thank you. :)

**Comment by winlee68** [comment]
what ?

**Comment by roseline124** [comment]
> what ?

what what?

**Comment by winlee68** [comment]
Are you Korean?

**Comment by roseline124** [comment]
No, I'm alien

**Comment by roseline124** [comment]
https://d2.naver.com/helloworld/59361 
I found this! sorry.

**Comment by cwdoh** [comment]
@roseline124 Thanks for asking to translate articles into Korean. If you're interested in under the hood of browser, I highly recommend [these articles](https://developers.google.com/web/updates/2018/09/inside-browser-part1). Thanksfuly they're translated, and also so many another untranslated articles are waiting for you at [here](https://github.com/google/WebFundamentals). 😀

**Comment by roseline124** [comment]
> @roseline124 Thanks for asking to translate articles into Korean. If you're interested in under the hood of browser, I highly recommend [these articles](https://developers.google.com/web/updates/2018/09/inside-browser-part1). Thanksfuly they're translated, and also so many another untranslated articles are waiting for you at [here](https://github.com/google/WebFundamentals). 😀

I see now, sorry 😂. thank you for your suggestion. I'm gonna read those articles :)
