### ISSUE TITLE
Vibration API Tutorial

### ISSUE THREAD

**Issue by KraigWalker** [html5rocks/www.html5rocks.com#297]
![html5vibration](https://f.cloud.github.com/assets/1294877/165086/e8d247fc-7916-11e2-816d-dfd4847eaf89.png)

## Prelude ##

I've been getting my teeth cut working on a browser game for work. One of the fun little additions we've added is support for the [HTML5 Gamepad API](http://www.w3.org/TR/gamepad/). Reading button presses off an Xbox 360 controller was easy enough; but then we just had to ask **"What About Force Feedback? It's been in controllers since the 90's. Right?"**

After a couple of emails to the editors of the Gamepad API demanding to know where our precious rumble pak was, [Scott Graham](http://www.h4ck3r.net) got in touch, saying the feature had been *"lightly discussed"* in the early days of the Gamepad API, and has since now taken a form of it's own: **The Vibration API**

### And we were like... ###

![tumblr_mhu3981PA71s4woeho1_400](https://f.cloud.github.com/assets/1294877/165114/ae06fe58-7919-11e2-8c66-c865e94bbb16.jpeg)

## Say Hi to the HTML5 Vibration API ##

The Vibration API is one of few API specifically intended with gaming in mind. In contrast with the Gamepad API however, which is slowly building up a wider user base, many people I've spoken to, not to mention many documentation sources, didn't get the memo about also being able to make those gamepads wiggle.

It is logical however to keep the two API's separate however. Devices like the original Xperia Play come with their own gamepad and thumbsticks, it does not however have vibrating motors intended for gaming.

## What I'd Like To Do ##

I'd like to write a tutorial to get people up and running with the Vibration API. It's not the biggest, most complicated API in the world, but I feel it's the missing part of the Gamepad API that a lot of people aren't aware of. The biggest impact I think it can have is in getting the ball rolling with discussion on how the API can be improved on. The core topics being discussed in the tutorial would be:

* A high level **overview** of what the Vibration API does 
* What browsers currently **support** the API
* What **devices** should be used with Vibration
* A cross-browser friendly **method** of using Vibration in games and web apps
* Understanding how **vibration patterns** work
* Using patterns to create different types of **rumble effects** (with examples, of course)
* Some **limitations** to bear in mind
* What the **future** might hold for Vibration

## What I'm Also Going To Do ##

I'm going to address some awareness issues on projects like HTML5 Please, which doesn't yet list the API yet. 
Modernizr added support for detecting Vibration support in 2.6, which I'd like to use in my tutorial in a similar way to the [Gamepad API](http://www.html5rocks.com/en/tutorials/doodles/gamepad/) tutorial by Marcin Wichary.

### May The Force (Feedback) Be With You ###

**Comment by Polyducks** [comment]
I'm aware I'm conducting post necromancy here, but this is a discussion that had no real resolution.

I'd really like to see the rumble feature make it to web games. It adds an extra level of depth to the experience. As far as I'm aware, vibration support for game pads is not currently available in live or canary builds of browsers. Is this correct?

**Comment by KraigWalker** [comment]
Back when I proposed it the Vibration Spec was actually still in flux, but Mozilla had included support within Firefox in order to allow developers access to vibration in Firefox Phones (RIP) PhoneGap also replicated the API using a native bridge.

I had raised a question regarding gamepads in the mailing list way back then, and it became apparent that the vibration api wouldn't be a good fit for Game Pads. It's more focussed on supporting control of a mobile device's individual motor. Gamepads often have two or more motors of different sizes (the latest Xbox controller has four) – one typically provides a buzzing rumble and another serves as a 'kicker' for larger thumps and knocks.

So it was decided the vibration API would accept only a single array of vibration patterns at a time, and effect one global actuator on the device. It was recommended in order to achieve the desired level of fidelity of vibration on Game Pads that the JavaScript Game Pad API be worked upon instead to support the additional level of functionality.

This made sense, as the Game Pad API could squawk the device type, allowing the developer to provide the appropriate vibration patterns. A first party game controller may likely feel different from a third party one, as will a controller developed for a different console.

My only gripe is that this divides vibration support into two, and it may end up being the vibration API that winds up being redundant. As I type on this train, my phone's just given me a notification buzz with it's main actuator. But if I push down on a link a little harder a completely different motor springs into live along with some additional options on-screen. The strength of the Vibration API is it's simplicity, but it's also it's weakness as devices get more diverse.

**Comment by Polyducks** [comment]
Thank you so much for your depthy response.

It may well be that mobile devices move on from a single vibration motor - when that happens a new API will be required which would support all devices (including game pads). Do you think this is possible?

**Comment by KraigWalker** [comment]
I think there's more likelihood of a second level of support being added to the gamepad API. Personally I think it would be a more appropriate area to add to. Of course, if a touch screen phone were to adopt that, there'd have to be a way of declaring "I actually don't have buttons or joypads."

I haven't subscribed to the working group mailing list on either the gamepad api or vibration. I'd recommend you find the on the w3c site, read a little bit of the backlog, and maybe pop the question? The wonders of open standards! 😍👍🏻

**Comment by KraigWalker** [comment]
UPDATE: In the span since I looked at vibration a proposal to extend the Gamepad API with vibration has been introduced:

https://lists.w3.org/Archives/Public/public-webapps/2016AprJun/0052.html <https://lists.w3.org/Archives/Public/public-webapps/2016AprJun/0052.html>

**Comment by KraigWalker** [comment]
I’d recommend checking out https://iswebvrready.org/ <https://iswebvrready.org/> which goes into support for new extensions to the gamepad api, including touchpads and posable VR controllers
