### ISSUE TITLE
Client-side storage article - link to demo broken [moved]

### ISSUE THREAD

**Issue by ebidel** [html5rocks/www.html5rocks.com#52]
This is [Issue 574](http://code.google.com/p/html5rocks/issues/detail?id=574) moved from the [old Google Code project](http://code.google.com/p/html5rocks/) and added by 2011-07-13T14:04:18.000Z by [mahem...@gmail.com](http://code.google.com/u/106413090159067280619/). Please review that bug for more context and additional comments, but update this bug.

Original labels: Type-Bug, Priority-P2
### Original description

```
The link with text &quot;Try the Geo-Mood demo now.&quot; is broken. It should be pointing to the /offline/static/index.html location, where the demo resides.
```

**Comment by birdca** [comment]
it seems this link still broken, sent a pull request already~
