### ISSUE TITLE
Secure URLs

### ISSUE THREAD

**Issue by cirocosta** [html5rocks/www.html5rocks.com#957]
There is a clear reason for not using [Secure URLs](https://developers.google.com/appengine/docs/python/config/appconfig#Python_app_yaml_Secure_URLs)?

https://developers.google.com/appengine/docs/ssl

**Comment by bardiharborow** [comment]
Is there an update on this? Circumstances have changed somewhat since 2014, especially with the Let's Encrypt launch.
